name: GridTest01
favicon: null
layout_spectrum: 0.26481
typography_spectrum: 0.33799408678896725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0fdff'
    - '#626548'
    - '#dbb06b'
    - '#17140f'
    - '#9fcced'
  brandStrength: 0.07695703790523112
  lightness: 0.5028141564689577
  saturation: 0.642511460930109
  rhythmicContrast: 0.44634258444420993
purpose: []
