name: GridTest01
favicon: null
layout_spectrum: 0.9388480319175869
typography_spectrum: 0.33799408678896725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07695703790523112
  lightness: 0.5028141564689577
  saturation: 0.642511460930109
  rhythmicContrast: 0.44634258444420993
purpose: []
